In [1]:
import pandas as pd

In [2]:
pd

In [3]:
data = {
    "product":["laptop","mouse", "desk"],
    "category": ["technology","technology","furniture"],
    "price":[30000,500,4000]

}

In [4]:
df = pd.DataFrame(data)

In [23]:
df

  product    category  price
0  laptop  technology  30000
1   mouse  technology    500
2    desk   furniture   4000

In [6]:
df.head()

  product    category  price
0  laptop  technology  30000
1   mouse  technology    500
2    desk   furniture   4000

In [7]:
df.shape

(3, 3)

In [8]:
df.columns

Index(['product', 'category', 'price'], dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   3 non-null      object
 1   category  3 non-null      object
 2   price     3 non-null      int64
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [10]:
df.describe()

              price
count      3.000000
mean   11500.000000
std    16116.761461
min      500.000000
25%     2250.000000
50%     4000.000000
75%    17000.000000
max    30000.000000

In [11]:
df.isnull()

   product  category  price
0    False     False  False
1    False     False  False
2    False     False  False

In [13]:
df.isnull().sum()

product     0
category    0
price       0
dtype: int64

In [14]:
df["price"]

0    30000
1      500
2     4000
Name: price, dtype: int64

In [15]:
df["price"].mean()

np.float64(11500.0)

In [16]:
df["price"].sum()

np.int64(34500)

In [18]:
print(df["price"].sum())

34500

In [19]:
df["price"].max()

30000

In [21]:
df["price"].median()

4000.0

In [22]:
df["price"].min()

500

In [25]:
df [df["category"] == "technology"]

  product    category  price
0  laptop  technology  30000
1   mouse  technology    500

In [26]:
df[df["price"] > 1000]

  product    category  price
0  laptop  technology  30000
2    desk   furniture   4000

In [28]:
df [(df["category"] == "technology") & (df["price"] >1000)]

  product    category  price
0  laptop  technology  30000

In [30]:
df.sort_values("price")

  product    category  price
1   mouse  technology    500
2    desk   furniture   4000
0  laptop  technology  30000

In [32]:
df.sort_values("price", ascending= False)

  product    category  price
0  laptop  technology  30000
2    desk   furniture   4000
1   mouse  technology    500

In [34]:
df["category"].value_counts()

category
technology    2
furniture     1
Name: count, dtype: int64

In [35]:
df.groupby("category")["price"].mean()

category
furniture      4000.0
technology    15250.0
Name: price, dtype: float64

In [36]:
df.groupby("category")["price"].sum()

category
furniture      4000
technology    30500
Name: price, dtype: int64

In [37]:
df.groupby("category")["price"].agg(["sum","mean","max","min"])

              sum     mean    max   min
category
furniture    4000   4000.0   4000  4000
technology  30500  15250.0  30000   500

In [38]:
csv_data = """product,category,price
laptop,technology,30000
mouse,technology,500
desk,furniture,4000
chair,furniture,2500
"""

with open("products.csv", "w") as file:
  file.write(csv_data)

In [39]:
df_csv = pd.read_csv("products.csv")
df_csv

  product    category  price
0  laptop  technology  30000
1   mouse  technology    500
2    desk   furniture   4000
3   chair   furniture   2500

In [40]:
df_csv.head()

  product    category  price
0  laptop  technology  30000
1   mouse  technology    500
2    desk   furniture   4000
3   chair   furniture   2500

In [41]:
df_csv.shape

(4, 3)

In [42]:
df_csv.columns

Index(['product', 'category', 'price'], dtype='object')

In [43]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   4 non-null      object
 1   category  4 non-null      object
 2   price     4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [44]:
df_csv.describe()

              price
count      4.000000
mean    9250.000000
std    13907.432066
min      500.000000
25%     2000.000000
50%     3250.000000
75%    10500.000000
max    30000.000000

In [45]:
df_csv.isnull().sum()

product     0
category    0
price       0
dtype: int64