In [1]:
import pandas as pd

data = {
    "product_name": ["laptop","mouse","desk","chair",None],
    "category": ["technology","technology","furniture",None,"furniture"],
    "price":[30000,500,None,2500,4000],
    "order_date": ["2026-06-01", "2026-06-02", "wrong-date", "2026-06-04",None]
}

df = pd.DataFrame(data)

df

  product_name    category    price  order_date
0       laptop  technology  30000.0  2026-06-01
1        mouse  technology    500.0  2026-06-02
2         desk   furniture      NaN  wrong-date
3        chair        None   2500.0  2026-06-04
4         None   furniture   4000.0        None

In [2]:
df.isnull().sum()

product_name    1
category        1
price           1
order_date      1
dtype: int64

In [3]:
df.dropna()

  product_name    category    price  order_date
0       laptop  technology  30000.0  2026-06-01
1        mouse  technology    500.0  2026-06-02

In [4]:
df.fillna("unknown")

  product_name    category    price  order_date
0       laptop  technology  30000.0  2026-06-01
1        mouse  technology    500.0  2026-06-02
2         desk   furniture  unknown  wrong-date
3        chair     unknown   2500.0  2026-06-04
4      unknown   furniture   4000.0     unknown

In [5]:
df["price"].fillna(0)

0    30000.0
1      500.0
2        0.0
3     2500.0
4     4000.0
Name: price, dtype: float64

In [6]:
df["category"].fillna(0)

0    technology
1    technology
2     furniture
3             0
4     furniture
Name: category, dtype: object

In [7]:
df["category"] = df["category"].fillna("unknown")
df

  product_name    category    price  order_date
0       laptop  technology  30000.0  2026-06-01
1        mouse  technology    500.0  2026-06-02
2         desk   furniture      NaN  wrong-date
3        chair     unknown   2500.0  2026-06-04
4         None   furniture   4000.0        None

In [8]:
df["product_name"]= df["product_name"].fillna("unknown")
df

  product_name    category    price  order_date
0       laptop  technology  30000.0  2026-06-01
1        mouse  technology    500.0  2026-06-02
2         desk   furniture      NaN  wrong-date
3        chair     unknown   2500.0  2026-06-04
4      unknown   furniture   4000.0        None

In [12]:
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")
df

  product_name    category    price order_date
0       laptop  technology  30000.0 2026-06-01
1        mouse  technology    500.0 2026-06-02
2         desk   furniture      NaN        NaT
3        chair     unknown   2500.0 2026-06-04
4      unknown   furniture   4000.0        NaT

In [17]:
df["order_date"].isnull().sum()

np.int64(2)

In [18]:
df= df.dropna(subset=["order_date"])
df

  product_name    category    price order_date
0       laptop  technology  30000.0 2026-06-01
1        mouse  technology    500.0 2026-06-02
3        chair     unknown   2500.0 2026-06-04

In [20]:
df = df.sort_values("price",ascending=False)
df

  product_name    category    price order_date
0       laptop  technology  30000.0 2026-06-01
3        chair     unknown   2500.0 2026-06-04
1        mouse  technology    500.0 2026-06-02

In [21]:
df["category"].value_counts()

category
technology    2
unknown       1
Name: count, dtype: int64

In [22]:
df=df.rename(columns={"product_name":"product"})
df

  product    category    price order_date
0  laptop  technology  30000.0 2026-06-01
3   chair     unknown   2500.0 2026-06-04
1   mouse  technology    500.0 2026-06-02

In [24]:
df["price"]=df["price"].astype(int)
df

  product    category  price order_date
0  laptop  technology  30000 2026-06-01
3   chair     unknown   2500 2026-06-04
1   mouse  technology    500 2026-06-02

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 1
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product     3 non-null      object
 1   category    3 non-null      object
 2   price       3 non-null      int64
 3   order_date  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 120.0+ bytes

In [28]:
df.isnull().sum()

product       0
category      0
price         0
order_date    0
dtype: int64

In [30]:
df.to_csv("clean_products.csv", index=False)

In [31]:
pd.read_csv("clean_products.csv")

  product    category  price  order_date
0  laptop  technology  30000  2026-06-01
1   chair     unknown   2500  2026-06-04
2   mouse  technology    500  2026-06-02